# Numpy 함수

# 하나의 array에 적용 (단항 유니버셜함수)

유니버셜함수 : ndarray안에 있는 데이터의 요소별로 연산을 수행해주는 함수

In [4]:
import numpy as np

ar1 = np.random.randn(5, 3)
ar1

array([[-0.70740513, -1.28455198,  1.57727884],
       [ 1.20266219,  0.01406591, -0.31604788],
       [-1.27449227,  0.11041831, -0.4996595 ],
       [-1.45544791,  1.02357525, -0.31380887],
       [ 0.158704  , -0.06774853,  0.54374749]])

In [5]:
# 각 요소의 절대값 ( == ar1 ** 0.5)
np.sqrt(ar1)

<ipython-input-5-d6d0ed8756e7>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(ar1)


array([[       nan,        nan, 1.25589762],
       [1.09665956, 0.11859979,        nan],
       [       nan, 0.33229251,        nan],
       [       nan, 1.01171896,        nan],
       [0.3983767 ,        nan, 0.73739236]])

In [6]:
# 각 요소의 제곱 계산
np.square(ar1)

array([[5.00422012e-01, 1.65007378e+00, 2.48780855e+00],
       [1.44639635e+00, 1.97849799e-04, 9.98862655e-02],
       [1.62433054e+00, 1.21922033e-02, 2.49659617e-01],
       [2.11832862e+00, 1.04770630e+00, 9.84760045e-02],
       [2.51869582e-02, 4.58986351e-03, 2.95661337e-01]])

In [7]:
# 각 요소를 자연로그, 상용로그, 아래가 2인 로그를 씌운 값 계산
print(np.log(ar1))
print()
print(np.log10(ar1))
print()
print(np.log2(ar1))

[[        nan         nan  0.45570111]
 [ 0.18453759 -4.2640012          nan]
 [        nan -2.2034793          nan]
 [        nan  0.02330165         nan]
 [-1.84071448         nan -0.60927031]]

[[        nan         nan  0.19790848]
 [ 0.08014366 -1.85183219         nan]
 [        nan -0.9569589          nan]
 [        nan  0.01011978         nan]
 [-0.79941214         nan -0.26460273]]

[[        nan         nan  0.65743773]
 [ 0.26623147 -6.15165339         nan]
 [        nan -3.17894866         nan]
 [        nan  0.03361717         nan]
 [-2.65558965         nan -0.87899125]]


<ipython-input-7-9ac07f5d57b3>:2: RuntimeWarning: invalid value encountered in log
  print(np.log(ar1))
<ipython-input-7-9ac07f5d57b3>:4: RuntimeWarning: invalid value encountered in log10
  print(np.log10(ar1))
<ipython-input-7-9ac07f5d57b3>:6: RuntimeWarning: invalid value encountered in log2
  print(np.log2(ar1))


In [8]:
# 각 요소의 부호 나타내기 (양수 : 1, 음수 : -1, 0 : 0)
np.sign(ar1)

array([[-1., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [ 1., -1.,  1.]])

In [9]:
# 각 요소의 소수 첫번째 자리에서 올림한 값 계산
np.ceil(ar1)

array([[-0., -1.,  2.],
       [ 2.,  1., -0.],
       [-1.,  1., -0.],
       [-1.,  2., -0.],
       [ 1., -0.,  1.]])

In [11]:
# 각 요소의 소수 첫번째 자리에서 버림한 값 계산
np.floor(ar1)

array([[-1., -2.,  1.],
       [ 1.,  0., -1.],
       [-2.,  0., -1.],
       [-2.,  1., -1.],
       [ 0., -1.,  0.]])

In [14]:
# 각 요소의 소수 첫번재 자리에서 반올림한 값 계산
np.round(ar1)

array([[-1., -1.,  2.],
       [ 1.,  0., -0.],
       [-1.,  0., -0.],
       [-1.,  1., -0.],
       [ 0., -0.,  1.]])

In [15]:
# 각 요소가 nan인 경우 True, 아닌 경우 False를 반환
np.isnan(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
# 각 요소가 무한대인 경우 True, 아닌 경우 False를 반환
np.isinf(ar1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [18]:
# 각 요소에 대해 삼각함수 값을 계산하기 (cos, cosh, sin, sinh, tan, tanh)
# ~h : 쌍곡선 함수
# 쌍곡선 ; 고정된 두 초점으로부터 거리가 일정한 점들에 의해 나타나는 곡선
np.cos(ar1)

array([[ 0.76005075,  0.28235139, -0.00648247],
       [ 0.35987521,  0.99990108,  0.9504712 ],
       [ 0.29198733,  0.99391009,  0.87774575],
       [ 0.1150928 ,  0.52031611,  0.95116474],
       [ 0.98743293,  0.99770595,  0.85577594]])

# 두 개의 array에 적용 (이항 유니버셜함수)

In [20]:
ar1

array([[-0.70740513, -1.28455198,  1.57727884],
       [ 1.20266219,  0.01406591, -0.31604788],
       [-1.27449227,  0.11041831, -0.4996595 ],
       [-1.45544791,  1.02357525, -0.31380887],
       [ 0.158704  , -0.06774853,  0.54374749]])

In [21]:
ar2 = np.random.randn(5, 3)
ar2

array([[ 1.25990794, -0.50193909,  1.8067344 ],
       [-0.78670155, -1.70961481, -0.64067061],
       [ 1.68564058,  1.73092163, -0.82618155],
       [ 0.82300485, -1.3412804 ,  2.21589488],
       [ 1.76348332,  0.20333351, -0.5567178 ]])

In [22]:
# 두 개의 array에 대해 동일한 위치 요소끼리
# 연산 값을 계산함수 (add, subtract, multiply, divide)
np.multiply(ar1, ar2)

array([[-0.89126534,  0.64476686,  2.84972395],
       [-0.9461362 , -0.02404729,  0.20248259],
       [-2.14833589,  0.19112544,  0.41280946],
       [-1.19784069, -1.37290142, -0.69536746],
       [ 0.27987185, -0.01377555, -0.30271391]])

In [34]:
# 두 개의 array에 대해 동일한 위치의 요소끼리 비교해서 최대값 or 최소값 계산
#   (maximum, minimum)
np.maximum(ar1, ar2)

[[-2.51862869e-01 -1.56237597e+00  3.06296708e-01]
 [-1.40678623e-01 -8.29270213e-01 -4.95578079e-01]
 [-1.43362626e-02 -1.38162805e+00  2.35164409e+00]
 [ 6.99391079e-01  1.39349637e-01  1.76714585e-01]
 [ 6.17595551e-02  3.61784239e-02  1.86125543e-03]]


array([[ 1.25990794, -0.50193909,  1.8067344 ],
       [ 1.20266219,  0.01406591, -0.31604788],
       [ 1.68564058,  1.73092163, -0.4996595 ],
       [ 0.82300485,  1.02357525,  2.21589488],
       [ 1.76348332,  0.20333351,  0.54374749]])

# 통계 함수

통계 함수를 통해서 array의 합이나 평균 등을 구할 때

추가로 'axis'라는 파라미터에 대한 값을 지정해서

열 또는 행의 합 또는 평균 드을 구할 수 있음 !

In [29]:
# 열 간의 합을 계산 (axis = 0)
np.sum(ar1, axis=0)

array([-2.07597912, -0.20424104,  0.99151008])

In [31]:
# 행 간의 합을 계산 (axis = 1)
np.sum(ar1, axis=1)

array([-0.41467826,  0.90068022, -1.66373346, -0.74568152,  0.63470296])

In [49]:
# 전체 요소의 평균을 계산
np.mean(ar1)

[[-0.70740513 -1.28455198  1.57727884]
 [ 1.20266219  0.01406591 -0.31604788]
 [-1.27449227  0.11041831 -0.4996595 ]
 [-1.45544791  1.02357525 -0.31380887]
 [ 0.158704   -0.06774853  0.54374749]]


0.3002267385417445

In [35]:
# 전체 요소의 표준편차, 분산, 최소값, 최대값 (std, var, min, max)
# 표준편차 : 데이터가 평균으로부터 얼마나 흩어져있는지를 나타내는 지표
# 분산 : 데이터가 평균으로부터 얼마나 멀리 떨어져있는지를 측정하는 지표
np.std(ar1)

0.877503960019814

In [40]:
# 전체 요소의 최소값, 최대값이 위치한 인덱스의 위치를 반환 (argmin, argmax)
np.argmin(ar1)


-0.49965950107654733

In [41]:
# 맨 처음 요소부터 각 요소까지의 누적합 or 누적곱을 계산 (cumsum, cumprod)
np.cumsum(ar1)

array([-0.70740513, -1.9919571 , -0.41467826,  0.78798393,  0.80204984,
        0.48600196, -0.78849031, -0.678072  , -1.1777315 , -2.63317941,
       -1.60960416, -1.92341302, -1.76470903, -1.83245756, -1.28871007])

In [43]:
# 사분위수 : 사분위수는 데이터를 4등분 한 것

# 0.25 : 1 사분위수 / 0.5 : 2 사분위수 (중앙값) / 0.75 : 3 사분위수
np.quantile(ar1, [1/4, 0.5, 0.75])

array([-0.60353231, -0.06774853,  0.35122574])

기타 함수

In [44]:
# 전체 요소에 대해서 오름차순 정렬
np.sort(ar1)

array([[-1.28455198, -0.70740513,  1.57727884],
       [-0.31604788,  0.01406591,  1.20266219],
       [-1.27449227, -0.4996595 ,  0.11041831],
       [-1.45544791, -0.31380887,  1.02357525],
       [-0.06774853,  0.158704  ,  0.54374749]])

In [45]:
# 열 방향으로 오름차순 정렬
np.sort(ar1, axis=0)

array([[-1.45544791, -1.28455198, -0.4996595 ],
       [-1.27449227, -0.06774853, -0.31604788],
       [-0.70740513,  0.01406591, -0.31380887],
       [ 0.158704  ,  0.11041831,  0.54374749],
       [ 1.20266219,  1.02357525,  1.57727884]])

In [46]:
# zip 함수
# 각 객체들을 파라미터로 받고, 그 요소들을 tuple의 형태로 반환
numbers = [1, 2, 3]
letters = ['A', 'B', 'C']
for pair in zip(numbers, letters):
  print(pair)

(1, 'A')
(2, 'B')
(3, 'C')
